[package]
name = "webassembly"
version = "0.1.1"
authors = ["Richard Anaya"]
edition = "2018"
description = "a library for working with web assembly"
license = "MIT OR Apache-2.0"
repository = "https://www.github.com/richardanaya/webassembly"